In [1]:
import numpy as np

In [3]:
from time import process_time

In [4]:
python_list = [i for i in range(1000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print(end_time - start_time)
# print(start_time)

0.0


In [5]:
np_array = np.array([i for i in range(1000)])
start_time = process_time()
np_array += 5
end_time = process_time()
print(end_time - start_time)


0.0


In [6]:
list1 = [1, 6, 7, 2, 7]
type(list1)

np_array = np.array([1, 6, 7, 2, 7])
type(np_array)

numpy.ndarray

In [7]:
# a = np.array([1, 2, 3, 4])
# print(a)
# a.shape

b = np.array([(1, 2, 3, 4), (5, 6, 7, 8)])
print(b)
b.shape #dimantion of an array

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [8]:
c = np.array([(0, 2, 3, 4), (5, 6, 7, 8)], dtype=float)
print(c)


[[0. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [9]:
d = np.zeros((4,5))
print(d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
e = np.ones((4,5))
print(e)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
f = np.full((4,5), 5) # Array of spacific number
print(f)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [12]:
f = np.identity(4) #Identity matrix
print(f)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
g = np.eye(4,5) #Identity matrix
print(g)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [14]:
# Random int value array in spacific length
i = np.random.randint(1,500000,(3,5))
print(i)

[[456809  14358  34737  75158  46348]
 [374443  44609 247862 458777 340851]
 [ 57548  80159 252198  86644   4779]]


In [15]:
j = np.linspace(10, 30, 6) #arrray of evenly spaced
print(j)

[10. 14. 18. 22. 26. 30.]


In [16]:
k = np.arange(10, 30, 5) #array of evenly spaced values
print(k)

[10 15 20 25]


In [17]:
# convert list into array
list2 = [10, 20, 30, 40, 50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

In [18]:
l = np.random.randint(10, 80, (5,5))
print(l)

[[35 48 16 42 43]
 [10 20 48 69 39]
 [18 23 44 10 67]
 [17 33 57 11 18]
 [76 76 69 60 20]]


In [19]:
print(l.ndim) #Dimention of array

2


In [20]:
# Number of element in the array
print(l.size)

25


In [21]:
list1 = [1, 4, 8, 7, 52, 2]
list2 = [4, 8,9,1,6,7]
print(list1+list2) #Concat the array not add the element

[1, 4, 8, 7, 52, 2, 4, 8, 9, 1, 6, 7]


In [22]:
m = np.random.randint(0, 10, (3, 3))
n = np.random.randint(10, 20, (3, 3))
print(m)
print(n)

[[8 5 4]
 [8 8 6]
 [8 9 6]]
[[17 16 19]
 [17 18 10]
 [19 16 11]]


In [23]:
print(m+n)

[[25 21 23]
 [25 26 16]
 [27 25 17]]


In [24]:
print(m-n)

[[ -9 -11 -15]
 [ -9 -10  -4]
 [-11  -7  -5]]


In [25]:
print(m/n)

[[0.47058824 0.3125     0.21052632]
 [0.47058824 0.44444444 0.6       ]
 [0.42105263 0.5625     0.54545455]]


In [26]:
print(np.add(m,n)) #Do insted of m + n
print(np.subtract(m,n)) #Do insted of m - n
print(np.multiply(m,n)) #Do instade of m * n
print(np.divide(m,n))

[[25 21 23]
 [25 26 16]
 [27 25 17]]
[[ -9 -11 -15]
 [ -9 -10  -4]
 [-11  -7  -5]]
[[136  80  76]
 [136 144  60]
 [152 144  66]]
[[0.47058824 0.3125     0.21052632]
 [0.47058824 0.44444444 0.6       ]
 [0.42105263 0.5625     0.54545455]]


In [27]:
array = np.random.randint(0, 10, (2,3))
print(array)
print(array.shape)

[[0 6 8]
 [4 6 8]]
(2, 3)


In [28]:
# Transpose array
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[0 4]
 [6 6]
 [8 8]]
(3, 2)


In [29]:
a = np.random.randint(0, 10, (5, 6))
print(a)

[[7 8 6 7 5 7]
 [1 3 0 8 1 7]
 [3 4 4 2 2 9]
 [3 4 5 5 6 9]
 [6 8 0 7 5 4]]


In [30]:
x = np.random.randint(100)
print(x)


32


In [32]:
x=np.random.randint(100, size=(5))

print(x)

[31 77 22 84 46]


In [38]:
z = np.array([1, 8, 6, 4, 2, 3]) # Shuffle data in the array
np.random.shuffle(z)
print(z)

[8 3 2 6 1 4]


In [45]:
print(np.random.permutation(z))

[1 3 6 4 2 8]
